/* General-supervision references for the state profiles:
   - each state's SPP/APR determination-letter file (OSEP), by two-letter code,
   - recent Differentiated Monitoring and Support (DMS) reports with key OSEP findings, and
   - special-education personnel (percent of teachers fully certified), national + by state.
   The DMS list covers 2021 through 2026: 44 Part B and Part C monitoring reports whose key
   findings were extracted directly from each report PDF, plus the related status, notification,
   and closeout letters that track each review to completion. Links point to ed.gov where the
   document is still hosted there, otherwise to the public specialeducationaction.com archive of
   the same OSEP document. The full history lives in OSEP's searchable database (window.DMS.db). */
window.DMS = {
  overview: 'Through Differentiated Monitoring and Support (DMS 2.0), OSEP monitors every state\u2019s IDEA Part B and Part C programs on a five-year cycle, reviewing general supervision, data (the SPP/APR), fiscal management, and dispute resolution, plus state-specific focus areas chosen by risk.',
  db: 'https://www.ed.gov/laws-and-policy/individuals-disabilities/idea/idea-differentiated-monitoring-and-support-dms-reports',
  sppLetter: function (ab, part) { return 'https://sites.ed.gov/idea/files/' + ab + '-' + (part || 'B') + '-SPP-APR-FFY23.docx'; },
  reports: {
    "AK": [
      { part: 'B', date: 'February 2026', iso: '2026-02-18', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/f9c5d4c1-61a9-4dd4-b929-56dc3ce1a668.pdf', insights: [] },
      { part: 'B', date: 'May 2024', iso: '2024-05-16', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/fd9633db-6c11-4a43-a88f-3b89edf97b0f.pdf', insights: [] },
      { part: 'B', date: 'September 2023', iso: '2023-09-25', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/bcb01537-777a-40e7-96ea-1410816eeb49.pdf', insights: ['In the general supervision area of identification and correction of noncompliance, OSEP found that the State does not have a general supervision system reasonably designed to ensure that its examination of data collected through its data system is used to identify LEA noncompliance and verify its correction, and that the State does not issue findings of noncompliance within a reasonable period of time after noncompliance is identified through its supplemental data collection, as required under 34 C.F.R. sections 300.149 and 300.600 through 300.602.','In the fiscal management area of subrecipient monitoring, OSEP found that the State does not have a reasonably designed system, policies and procedures, and internal controls for its subrecipient monitoring process, consistent with 2 C.F.R. sections 200.332(b), (d)-(f) and (h), 200.339, and 200.403 and 34 C.F.R. sections 300.149 and 300.600.'] },
    ],
    "AR": [
      { part: 'B', date: 'January 2025', iso: '2025-01-16', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/f56cfd29-fb3f-4293-8c14-8a57ac9fe327.pdf', insights: [] },
      { part: 'C', date: 'July 2024', iso: '2024-07-17', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/eaee9636-32be-4186-8520-f4be8827bce0.pdf', insights: [] },
      { part: 'B', date: 'March 2024', iso: '2024-03-21', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/27547fb6-e718-416e-b108-90978990eb6d.pdf', insights: [] },
      { part: 'B', date: 'September 2023', iso: '2023-09-28', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/e5853d47-66cf-4014-84a3-dd3012d4ac99.pdf', insights: ['In the general supervision area of identification of noncompliance, OSEP found that the State does not have a general supervision system reasonably designed to identify noncompliance in a timely manner as required under 34 C.F.R. sections 300.149 and 300.600 through 300.602, because the State\'s policies resulted in written findings issued to LEAs 180 days or more after the monitoring activity rather than generally within three months of the State\'s identification of noncompliance.','In the significant disproportionality component, OSEP identified no noncompliance but noted an area of concern that the State\'s written policies and procedures under 34 C.F.R. section 300.173 do not explicitly describe all of the required activities under 34 C.F.R. section 300.646(c) and (d) for LEAs identified with significant disproportionality, and issued recommendations rather than a finding.'] },
      { part: 'C', date: 'January 2023', iso: '2023-01-12', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/06cdc275-1e4a-42d6-b2cf-9bd36bd28574.pdf', insights: ['In the area of general supervision, OSEP found that the State does not have a general supervision system that, in its entirety, is reasonably designed to identify and verify correction of noncompliance in a timely manner, because the lead agency issues findings only for SPP/APR compliance indicators rather than all IDEA Part C requirements, as required under 34 C.F.R. sections 303.120 and 303.700 through 303.702.','In the area of fiscal management under the single line of responsibility, OSEP found that the State does not conduct fiscal monitoring as required under 34 C.F.R. section 303.120(a)(1) and has not established effective internal controls that provide reasonable assurance of its EIS providers\' compliance with Federal statutes, regulations, and the terms and conditions of the Federal award, as required under 2 C.F.R. section 200.303.'] },
    ],
    "AS": [
      { part: 'B', date: 'May 2025', iso: '2025-05-16', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/46a2184a-1725-4187-9151-f7b56b596543.pdf', insights: ['OSEP finds that in the area of general supervision, the American Samoa Department of Education does not have policies and procedures documented in its monitoring manual that are consistent with its practice to identify noncompliance and ensure the implementation of IDEA Part B, as required under 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.606 through 300.608.','OSEP finds that in the area of fiscal management, the American Samoa Department of Education does not have a system in place to establish that IDEA funds have been used in accordance with Federal requirements and the terms and conditions of the grant award, as required under 2 C.F.R. section 200.302(a), or to maintain effective internal control providing reasonable assurance it is managing the IDEA Part B administrative funds in compliance, as required under 2 C.F.R. section 200.303.'] },
      { part: 'C', date: 'September 2024', iso: '2024-09-12', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/e7e54d9d-f450-4f32-b9d6-c3bbbd20def2.pdf', insights: ['Under the general supervision and monitoring component, OSEP found that the American Samoa Department of Health does not have written policies for monitoring the provision of IDEA Part C, including policies documenting its procedures for identifying and verifying the correction of noncompliance, that demonstrate compliance with 34 C.F.R. sections 303.120, 303.700 through 303.702, and 303.706 through 303.708.','Under the dispute resolution component, OSEP found that the American Samoa Department of Health does not have procedures that meet the mediation requirements in 34 C.F.R. sections 303.430(b) and 303.431(b)(2)(i) and (ii), because it neither maintains a list of qualified, knowledgeable mediators nor has a process for selecting mediators on a random, rotational, or otherwise impartial basis.'] },
      { part: 'B', date: 'April 2024', iso: '2024-04-02', kind: 'Fiscal monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/282adf92-fc52-41b0-9de9-0d8c2742d063.pdf', insights: ['In the fiscal management (monitoring) area, OSEP found that the American Samoa Government, including ASDOE and ASDOH, does not have a system of fiscal monitoring reasonably designed to provide oversight of the Consolidated Grant and IDEA programs and is therefore not in compliance with 2 C.F.R. sections 200.329(a) and 200.303(c), nor with the IDEA general supervisory responsibilities in 34 C.F.R. sections 300.149, 300.600, and 303.120.','In the fiscal management (internal controls) area, OSEP found that ASDOE and ASDOH do not have a system of internal controls reasonably designed to ensure that their policies and procedures reflect program practices for contract oversight, record retention, procurement, and prior approval, as required under 2 C.F.R. section 200.303.'] },
      { part: 'C', date: 'March 2024', iso: '2024-03-29', kind: 'Fiscal monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/087fa2d8-1b43-4697-aa6c-9d492fc4ecb1.pdf', insights: ['OSEP found that American Samoa, including the American Samoa Department of Education and the American Samoa Department of Health (which administers the Part C program, Helping Hands), does not have a system of fiscal monitoring reasonably designed to provide oversight of the IDEA and Consolidated Grant programs, and is therefore not in compliance with 2 C.F.R. sections 200.329(a) and 200.303(c) or with the IDEA general supervisory responsibilities in 34 C.F.R. sections 300.149, 300.600, and 303.120.','OSEP found that the American Samoa Department of Education and the American Samoa Department of Health lack a system of internal controls reasonably designed to ensure that their written policies and procedures reflect actual program practices for contract oversight, record retention, procurement, and prior approval, and are therefore not in compliance with 2 C.F.R. section 200.303.'] },
    ],
    "AZ": [
      { part: 'B', date: 'March 2023', iso: '2023-03-01', kind: 'Closeout letter', url: 'https://www.ed.gov/sites/ed/files/fund/data/report/idea/partbdmsrpts/dms-az-b-2023-letter-03-01-2023.pdf', insights: [] },
    ],
    "BIE": [
      { part: 'B', date: 'September 2021', iso: '2021-09-08', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/e25538c7-c9c0-495d-8514-82f17cd2deb6.pdf', insights: [] },
      { part: 'B', date: 'September 2021', iso: '2021-09-08', kind: 'Summary chart', url: 'https://www.specialeducationaction.com/api/v1/file/d1c02f00-cf0c-4cfb-85e9-b282c6b3acb0.pdf', insights: [] },
    ],
    "CO": [
      { part: 'C', date: 'December 2024', iso: '2024-12-20', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/c4511f86-1ed2-4e9e-ad76-5495acd3a0d7.pdf', insights: [] },
      { part: 'B', date: 'May 2024', iso: '2024-05-16', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/7ffff1dc-bae7-4e5e-a941-f34308dbda96.pdf', insights: ['Under general supervision monitoring, OSEP finds that the State was unable to provide evidence of the implementation of its responsibility for programmatic monitoring under IDEA Part B that demonstrates compliance with the monitoring and enforcement requirements in 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.606 through 300.608, including monitoring beyond the SPP/APR indicators.','Under fiscal management and subrecipient monitoring, OSEP finds that the State does not have a reasonably designed general supervision system, including policies and procedures, for subrecipient monitoring and fiscal management consistent with 2 C.F.R. sections 200.332(b), (d)-(f) and (h), 200.339, and 34 C.F.R. sections 300.149, 300.600 through 602, and 300.604.'] },
      { part: 'C', date: 'April 2024', iso: '2024-04-29', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/dfac6796-1683-4045-babe-b85bd1dcc167.pdf', insights: ['OSEP found that Colorado does not have a general supervision system reasonably designed to identify noncompliance, because the State established no monitoring policies and procedures for its 16 evaluation entities and had not completed monitoring of its EIS providers since SFY 2020, as required under 34 C.F.R. sections 303.120 and 303.700 through 303.702.','OSEP found that the State does not have a general supervision system with policies and procedures reasonably designed to monitor its EIS providers for compliance with IDEA Part C fiscal requirements, such as coordination of all available funding sources and payor of last resort, as required under 2 C.F.R. sections 200.329(a) and 200.303 and IDEA Part C requirements in 34 C.F.R. sections 303.120(a), 303.500 through 303.510, and 303.520 through 303.521.'] },
    ],
    "FL": [
      { part: 'B', date: 'March 2023', iso: '2023-03-02', kind: 'Closeout letter', url: 'https://www.ed.gov/sites/ed/files/fund/data/report/idea/partbdmsrpts/dms-fl-b-2023-letter-03-02-2023.pdf', insights: [] },
    ],
    "IA": [
      { part: 'B', date: 'July 2025', iso: '2025-07-16', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/b0a220d5-fb6c-4cf4-a929-3ca5e794663f.pdf', insights: ['Under general supervision, OSEP found that the State does not have a general supervision system reasonably designed to identify noncompliance with all IDEA Part B requirements in a timely manner, because the State delays issuing a finding on confirmed systemic noncompliance in a district until it completes a second monitoring process investigating additional districts, as required by 34 C.F.R. sections 300.149, and 300.600 through 300.602.','In the area of fiscal management and subrecipient monitoring, OSEP found that the State does not have a reasonably designed general supervision system, including policies and procedures for subrecipient monitoring, fiscal management, and internal controls, consistent with 2 C.F.R. sections 200.332, 200.339, 200.303, and 34 C.F.R. sections 300.149, 300.600, and 300.604.'] },
      { part: 'C', date: 'June 2025', iso: '2025-06-18', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/3e9123f9-2ed0-496d-ba35-9262f15c2c5b.pdf', insights: ['In the area of general supervision and fiscal management, OSEP found that the State does not have a general supervision system reasonably designed to monitor local educational agencies and ensure compliance with the IDEA Part C fiscal requirements, including use of funds, payor of last resort, and the system of payments, as required by 2 C.F.R. sections 200.329(a) and 200.303 and 34 C.F.R. sections 303.120(a), 303.500 through 303.510, and 303.520 through 303.521.','In the area of dispute resolution, OSEP found that the State\'s mediation policies and procedures are inconsistent with the IDEA Part C requirements in 34 C.F.R. section 303.431 because the State\'s general dispute resolution webpage presents an Area Education Agency mediation process alongside the IDEA Part C mediation process without clearly identifying the mediation requirements and protections afforded to parents under IDEA Part C.'] },
    ],
    "ID": [
      { part: 'C', date: 'February 2026', iso: '2026-02-18', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/366c59b0-f181-4d11-92ba-764b8cb8ff3b.pdf', insights: [] },
      { part: 'B', date: 'May 2025', iso: '2025-05-16', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/4ad843a4-934a-49ae-afa6-0959518e12c9.pdf', insights: ['On general supervision, OSEP finds that the State does not have a reasonably designed general supervision system to ensure the identification of noncompliance and that each educational program for children with disabilities meets the IDEA Part B requirements under 34 C.F.R. sections 300.149 and 300.600 through 300.602, because the State allows LEAs to self-select a small number of files for review.','On correction of noncompliance, OSEP finds that the State does not have a general supervision system that is reasonably designed to verify the correction of noncompliance as required by 34 C.F.R. section 300.600(e), because it allows LEAs to self-select evidence and to submit data predating the finding rather than updated data showing the LEA has achieved compliance.'] },
      { part: 'C', date: 'September 2024', iso: '2024-09-17', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/39cf21f5-a227-4ac6-9675-fc957884a48a.pdf', insights: ['In the area of general supervision monitoring, OSEP finds that the State\'s implementation of its general supervision system to monitor its early intervention service programs and providers does not ensure compliance with IDEA Part C requirements beyond the SPP/APR indicators, as required by 34 C.F.R. sections 303.120 and 303.700 through 303.702.','In the area of provision of early intervention services, OSEP finds that the State is unable to ensure that all early intervention services addressing the unique needs of the child are included in the IFSP, with parent involvement, and that all early intervention services are timely provided to all eligible infants and toddlers with disabilities and their families, as required by 34 C.F.R. sections 303.112, 303.340, and 303.342(e).'] },
      { part: 'B', date: 'June 2024', iso: '2024-06-25', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/231ebb5c-40d0-44c2-8ebe-5d356da37872.pdf', insights: [] },
      { part: 'B', date: 'October 2023', iso: '2023-10-20', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/11b18add-b904-418d-9b0a-fd79738eca65.pdf', insights: [] },
    ],
    "IN": [
      { part: 'C', date: 'July 2025', iso: '2025-07-28', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/44e9797a-3474-4aaf-8677-7d6e828fe9f8.pdf', insights: ['In the area of general supervision, OSEP finds that the State does not have a general supervision system that is reasonably designed to identify noncompliance with all IDEA Part C requirements in a timely manner, because it limits programmatic monitoring to the SPP/APR indicators and two State-identified indicators rather than all IDEA Part C requirements, as required by 34 C.F.R. sections 303.120, and 303.700 through 303.708.','In the area of timely early intervention services, OSEP finds that the State\'s IFSP forms and other State documentation contain provisions requiring a physician\'s signature of agreement before early intervention services may begin, creating a structural impediment to timely provision of services inconsistent with 34 C.F.R. sections 303.20(c), 303.342(e), and 303.344(f)(1).'] },
      { part: 'B', date: 'May 2025', iso: '2025-05-23', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/10f3d7c5-9849-4ea1-b953-d7872ead81db.pdf', insights: ['In the general supervision area of monitoring and improvement, OSEP finds that the State does not have a general supervision system that is reasonably designed to identify noncompliance with all IDEA Part B requirements in a timely manner, because the State limits its programmatic monitoring to the SPP/APR indicators, as required by 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.606 through 300.608.','In the area of fiscal management and subrecipient monitoring, OSEP finds that the State does not have a system for notifying LEAs of any noncompliance with subrecipient monitoring requirements or a mechanism to track correction of that noncompliance, as required by 2 C.F.R. section 200.332(d) and 34 C.F.R. sections 300.149, 300.600 through 602, and 300.604.'] },
    ],
    "KS": [
      { part: 'C', date: 'July 2025', iso: '2025-07-24', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/36d80abe-6e33-4f2c-bffc-86b55ec0d91e.pdf', insights: ['In the area of fiscal management and subrecipient monitoring, OSEP finds that the State does not have a general supervision system that is reasonably designed to monitor EIS providers and local lead/fiscal agencies to ensure compliance with IDEA Part C fiscal requirements (including use of funds, payor of last resort, and system of payments) and the OMB Uniform Guidance, as required by 34 C.F.R. sections 303.120(a), 303.226, 303.500 through 303.510, and 303.520 through 303.521, and 2 C.F.R. sections 200.329(a) and 200.303.','In the area of general supervision and monitoring, OSEP finds that the State does not have a general supervision system that is reasonably designed to monitor EIS programs to ensure compliance with the IDEA Part C requirements, because it identifies noncompliance only when data reflect SPP/APR indicators below 100 percent and reviews just one IFSP per program, as required by 34 C.F.R. sections 303.120, and 303.700 through 303.708.'] },
      { part: 'B', date: 'July 2025', iso: '2025-07-10', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/78999299-4445-423f-9412-b9c76f3346f3.pdf', insights: ['In the area of general supervision (identification of noncompliance), OSEP found that the State does not have a general supervision system reasonably designed to identify noncompliance with all IDEA Part B requirements in a timely manner, because it does not monitor the interlocals, special education cooperatives, or education service centers that operate as LEAs and is not making annual determinations for each such LEA, as required by 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.606 through 300.608.','In the area of data and the SPP/APR, OSEP found that the State does not have a reasonably designed data system to collect and report valid and reliable data, as required by 20 U.S.C. section 1416(b)(2)(B) and 34 C.F.R. sections 300.601(b) and 300.640 through 300.646.'] },
    ],
    "KY": [
      { part: 'C', date: 'January 2025', iso: '2025-01-08', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/ac016053-9ab6-4a15-b0a9-14fd29a98483.pdf', insights: [] },
      { part: 'B', date: 'April 2024', iso: '2024-04-29', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/cb063837-1233-469f-be99-ca4150745e04.pdf', insights: ['In the area of fiscal management and subrecipient monitoring, OSEP found that the State did not ensure that every IDEA Part B subgrant notification was clearly identified to the subrecipient as a subaward as required in 2 C.F.R. section 200.332(a), and that its subgrant notifications did not include an Assistance Listings Number as required in 2 C.F.R. section 200.332(a)(1)(xii).','OSEP further found that the State\'s October 1 IDEA Part B subgrant notification did not include the amount of Federal funds made available to the LEA on July 1 or the total amount of Federal funds obligated by the State to the LEA, including both the July 1 and October 1 payments, as required in 2 C.F.R. section 200.332(a)(1)(vii)-(viii).'] },
      { part: 'C', date: 'April 2024', iso: '2024-04-12', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/e7643d94-9dcd-4405-b5e6-8dfe8e300de7.pdf', insights: ['In the area of fiscal management and general supervision, OSEP found that the State does not have a general supervision system reasonably designed to monitor its early intervention service programs or providers to ensure fiscal compliance with IDEA Part C, as required under 34 C.F.R. sections 303.120, 303.205, 303.700 and 303.704, and with the OMB Uniform Guidance in 2 C.F.R. Part 200.','In the area of monitoring and improvement, OSEP found that the State is not ensuring that early intervention services are provided to all eligible infants and toddlers with disabilities and their families in a timely manner as required by 34 C.F.R. sections 303.112 and 303.342(e).'] },
    ],
    "LA": [
      { part: 'B', date: 'February 2026', iso: '2026-02-23', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/4091b50d-b389-47b9-a616-10b1931f26f4.pdf', insights: ['In the area of general supervision and the correction of noncompliance, OSEP found that the State was unable to provide evidence during the monitoring period that, when noncompliance had been identified, the LEA was correctly implementing the specific regulatory requirements based on a review of updated data confirming systemic compliance, as required by 34 C.F.R. sections 300.149 and 300.600(e).','In the area of dispute resolution, OSEP found that the State\'s regulations, procedural safeguards, and State complaint procedures contained language restricting the parties subject to the complaint procedures to LEAs rather than to all entities within IDEA\'s definition of public agency, which is inconsistent with 34 C.F.R. sections 300.33, 300.151, and 300.153(b).'] },
      { part: 'C', date: 'December 2025', iso: '2025-12-17', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/aae203c4-112b-4ea6-b6ac-6b6cb528c355.pdf', insights: ['In the area of general supervision monitoring and improvement, OSEP finds that the State identifies noncompliance with IDEA Part C requirements based only on a review of SPP/APR compliance indicator data and does not issue written findings to EIS programs or providers, in violation of 20 U.S.C. sections 1416(a), 1434, 1435(a)(10), and 1442, and 34 C.F.R. sections 303.120 and 303.700 through 303.708.','In the area of fiscal management and the single line of responsibility, OSEP finds that the State does not have a reasonably designed general supervision system with policies and procedures to monitor EIS programs or providers and ensure compliance with IDEA Part C fiscal requirements, including payor of last resort, as required by 34 C.F.R. sections 303.120(a), 303.500 through 303.510, and 303.520 through 303.521, and 2 C.F.R. sections 200.329(a) and 200.303.'] },
      { part: 'B', date: 'January 2022', iso: '2022-01-21', kind: 'Closeout letter', url: 'https://www.ed.gov/sites/ed/files/fund/data/report/idea/partbdmsrpts/dms-la-b-closeout-2022.pdf', insights: [] },
    ],
    "MA": [
      { part: 'B', date: 'January 2025', iso: '2025-01-16', kind: 'Targeted monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/176eeb5f-3b86-4452-98f9-bfb83720233a.pdf', insights: ['In the area of child find, OSEP finds that the State does not have a reasonably designed general supervision system to ensure that all children in need of special education and related services are identified, located, and evaluated under 34 C.F.R. section 300.111 and that public agencies initiate initial evaluations under 34 C.F.R. section 300.301, because the State does not monitor whether tiered interventions or screening tools are being used to delay or deny full evaluations of children suspected of having a disability.','In the area of dispute resolution, OSEP finds that the State does not have written State complaint procedures that ensure complaints are resolved consistent with the IDEA Part B regulations at 34 C.F.R. sections 300.151 through 300.153, relying instead on the general Problem Resolution System and on local self-investigation reports from LEAs rather than an independent SEA determination.'] },
    ],
    "ME": [
      { part: 'C', date: 'February 2026', iso: '2026-02-19', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/5423c915-1b81-4014-a912-7613f937a11a.pdf', insights: ['In the area of general supervision, OSEP finds that the State does not have a single line of responsibility for the general administration and supervision of programs and activities administered by agencies, institutions, organizations, and EIS providers receiving assistance under IDEA Part C, as required by 34 C.F.R. section 303.120.','In the area of general supervision and identification and correction of noncompliance, OSEP finds that the State does not have a system in place to monitor the IDEA Part C program, including identifying and verifying correction of noncompliance, issuing written notifications of noncompliance, and making annual determinations, as required under 34 C.F.R. sections 303.120 and 303.700 through 303.708.'] },
    ],
    "MI": [
      { part: 'C', date: 'March 2024', iso: '2024-03-12', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/2db38d30-808c-422e-938e-7c0666745998.pdf', insights: [] },
      { part: 'C', date: 'November 2023', iso: '2023-11-21', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/c9930ce8-fabb-4189-900e-42853cebe7f3.pdf', insights: [] },
      { part: 'C', date: 'January 2023', iso: '2023-01-12', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/47cfb95f-1995-4d73-bd3c-7d24188a8f3f.pdf', insights: ['In the area of general supervision and monitoring, OSEP found that the Michigan Department of Education does not have a general supervision system that is reasonably designed to monitor the provision of IDEA Part C services, and specifically lacks a mechanism to verify implementation of Individualized Family Service Plans at the local service area level, as required under 34 C.F.R. sections 303.120, 303.342(e), 303.344(d), and 303.700 through 303.702.','In the area of fiscal management under the single line of responsibility, OSEP found that the State does not conduct fiscal monitoring as required under 34 C.F.R. section 303.120(a)(1) for the payor of last resort and system of payment requirements, and does not consistently implement its statewide system of payment to ensure that IDEA Part C funds are not used for services that would otherwise be paid from another public or private source, as required under 34 C.F.R. sections 303.500, 303.510, 303.520, and 303.521.'] },
    ],
    "MS": [
      { part: 'B', date: 'July 2025', iso: '2025-07-23', kind: 'Targeted monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/b20a3fc5-a3a2-4343-89cd-69c884017bae.pdf', insights: ['OSEP found that the State does not have a general supervision system reasonably designed to identify noncompliance with all IDEA Part B requirements in a timely manner, because the State did not issue written notifications of noncompliance to LEAs generally within three months of identification and did not issue written findings when noncompliance was identified through its SPP/APR data system, as required by 34 C.F.R. sections 300.149, and 300.600 through 300.602.','OSEP found that the State does not have a general supervision system reasonably designed to verify the correction of systemic noncompliance in a timely manner, in part because it lacked a system to verify systemic correction for SPP/APR compliance indicators and allowed LEAs to self-select the files reviewed to demonstrate compliance, as required by 34 C.F.R. sections 300.149, and 300.600 through 300.602.'] },
      { part: 'C', date: 'May 2025', iso: '2025-05-19', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/757583f9-c185-4e0d-862e-9c191fb7fc00.pdf', insights: ['In the area of general supervision, OSEP found that the State does not have a general supervision system that is reasonably designed to identify noncompliance with all IDEA Part C requirements in a timely manner, as required by 34 C.F.R. sections 303.120, and 303.700 through 303.702, because the State does not issue written findings to early intervention service programs or providers generally within three months of identifying noncompliance.','In the area of fiscal management, OSEP found that the State does not have a reasonably designed general supervision system that includes policies and procedures to monitor early intervention service programs or providers and ensure compliance with IDEA Part C fiscal requirements, such as coordination of all available funding sources and payor of last resort, as required by 2 C.F.R. sections 200.329(a), 200.303, and 34 C.F.R. sections 303.120(a), 303.500 through 303.510, and 303.520 through 303.521.'] },
    ],
    "MT": [
      { part: 'B', date: 'September 2025', iso: '2025-09-10', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/c4c37bc3-1947-49ac-b527-03a8c86e7601.pdf', insights: [] },
      { part: 'C', date: 'May 2024', iso: '2024-05-21', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/3218f15f-37ff-4d37-8049-d1ba1d33cd10.pdf', insights: [] },
      { part: 'B', date: 'May 2024', iso: '2024-05-16', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/3a454d44-ebc6-468f-8657-ff099c7a0119.pdf', insights: ['In the area of general supervision, OSEP found that the State does not have a reasonably designed general supervision system to ensure the identification and timely correction of noncompliance and that each educational program for children with disabilities meets the IDEA Part B requirements under 34 C.F.R. sections 300.149 and 300.600 through 300.602.','In the area of fiscal management and subrecipient monitoring, OSEP found that the State does not have a reasonably designed system, policies and procedures, and internal controls for its subrecipient monitoring process consistent with 2 C.F.R. sections 200.332, 200.339, and 200.303 and 34 C.F.R. sections 300.149, 300.600, and 300.604.'] },
      { part: 'C', date: 'December 2023', iso: '2023-12-20', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/85d3d017-210e-408d-8b3c-c4b03810b974.pdf', insights: [] },
      { part: 'C', date: 'August 2023', iso: '2023-08-10', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/ed874e67-c1b4-45b6-8962-2b865dc37212.pdf', insights: [] },
      { part: 'C', date: 'January 2023', iso: '2023-01-24', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/164d74ef-da2f-44ee-ba0f-9b6f6935b49b.pdf', insights: ['Under general supervision, OSEP found that DPHHS does not have a system reasonably designed to monitor its EIS providers to ensure compliance with IDEA Part C requirements, including the timely provision of early intervention services so that there are no waitlists, as required under 34 C.F.R. sections 303.120(a) and 303.700.','In fiscal management under the single line of responsibility, OSEP found that DPHHS does not have a general supervision system reasonably designed to identify and verify correction of fiscal noncompliance, as required under 34 C.F.R. sections 303.120(a)(1) and (2) and 303.700(a) and (b), and lacks procedures reasonably designed to ensure the appropriate use of IDEA Part C funds under 34 C.F.R. sections 303.120(a) and 303.205 and the OMB Uniform Guidance in 2 C.F.R. Part 200.'] },
    ],
    "NC": [
      { part: 'B', date: 'August 2022', iso: '2022-08-03', kind: 'Closeout letter', url: 'https://www.ed.gov/sites/ed/files/fund/data/report/idea/partbdmsrpts/dms-nc-b-closeout-2022.pdf', insights: [] },
    ],
    "ND": [
      { part: 'B', date: 'July 2025', iso: '2025-07-17', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/9e1d9a2b-eebc-4989-b5ed-c6d2591b2f64.pdf', insights: ['OSEP found that the State does not have a general supervision system reasonably designed to identify noncompliance with all IDEA Part B requirements in a timely manner, because it limits programmatic monitoring to a sampling of only three LEAs each year rather than ensuring all LEAs are monitored at least once within a six-year period, as required by 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.606 through 300.608.','OSEP found that the State does not have a reasonably designed general supervision system, including policies and procedures, for subrecipient monitoring, lacking policies and procedures for fiscal monitoring and any evidence demonstrating subrecipient monitoring was conducted, consistent with 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.604, and 2 C.F.R. sections 200.332 and 200.303.'] },
      { part: 'C', date: 'July 2025', iso: '2025-07-17', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/79e92ca6-5df7-4918-94db-c5377dbdd2e3.pdf', insights: ['Under the general supervision monitoring and improvement component, OSEP found that the State does not have a general supervision system that is reasonably designed to identify noncompliance with all IDEA Part C requirements in a timely manner, because it identifies noncompliance only through a review of SPP/APR compliance indicator data rather than all IDEA Part C requirements, as required by 34 C.F.R. sections 303.120, and 303.700 through 303.708.','Under fiscal management, OSEP found that the State does not have a reasonably designed general supervision system that includes policies and procedures to monitor EIS programs or providers and ensure compliance with IDEA Part C fiscal requirements, such as coordination of all available funding sources and payor of last resort, as required by 2 C.F.R. sections 200.329(a), 200.303, and 34 C.F.R. sections 303.120(a), 303.500 through 303.510, and 303.520 through 303.521.'] },
    ],
    "NE": [
      { part: 'B', date: 'July 2025', iso: '2025-07-23', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/9e8f3e0d-8f11-40db-b8e2-2bba2f0a7b9c.pdf', insights: ['In the area of general supervision, OSEP found that the State does not have a general supervision system that is reasonably designed to identify noncompliance with IDEA Part B requirements in a timely manner, as required by 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.606 through 300.608, and 2 C.F.R. section 200.303(a), because the State relies on unverified LEA self-reported data rather than reviewing source documentation to confirm compliance.','In the area of fiscal management and subrecipient monitoring, OSEP found that the State does not have a reasonably designed general supervision system that is inclusive of the fiscal monitoring requirements under IDEA and the OMB Uniform Guidance, consistent with 34 C.F.R. sections 300.149, 300.600, and 300.604 and 2 C.F.R. sections 200.332 and 200.303, because its fiscal notifications of noncompliance omit required elements and it lacks a system to track and verify correction.'] },
    ],
    "NJ": [
      { part: 'B', date: 'July 2025', iso: '2025-07-14', kind: 'Targeted monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/58a62ae0-f059-4bfc-b731-dcac3648b1b9.pdf', insights: ['In the area of general supervision of dispute resolution, OSEP finds that the State is not ensuring due process complaints are decided in accordance with the timelines set forth in 34 C.F.R. sections 300.510(c), and 300.515(a) and (c).','In the area of data collection and reporting, OSEP finds that the State does not have a mechanism for collecting due process complaint data, as required by IDEA Sections 616 and 618 and 34 C.F.R. sections 300.601(b), and 300.640 through 300.646.'] },
      { part: 'B', date: 'December 2023', iso: '2023-12-15', kind: 'Notification of monitoring', url: 'https://www.specialeducationaction.com/api/v1/file/d1bff5ef-6ccd-4583-a07a-d6156902fb72.pdf', insights: [] },
      { part: 'B', date: 'October 2023', iso: '2023-10-20', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/d5fafbc3-86f3-4110-9e5e-14c99a31f378.pdf', insights: [] },
    ],
    "NV": [
      { part: 'C', date: 'July 2025', iso: '2025-07-10', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/700b9970-24f8-4b43-85ae-1a4c3b4a3e21.pdf', insights: ['Under fiscal management and general supervision, OSEP found that the State does not monitor for IDEA Part C fiscal requirements because it was unable to demonstrate that it has a system to identify and verify correction of noncompliance as part of its system of fiscal monitoring, as required by 2 C.F.R. sections 200.329(a) and 200.303 and IDEA Part C requirements in 34 C.F.R. sections 303.120(a), 303.500 through 303.510, and 303.520 through 303.521.','Under monitoring and improvement, OSEP found that the State does not ensure that the SEA and appropriate LEA receive notification of any infants or toddlers with disabilities who are identified as potentially eligible for preschool services under IDEA Part B consistent with 34 C.F.R. section 303.209(b).'] },
      { part: 'B', date: 'October 2024', iso: '2024-10-04', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/1dde9784-d90d-4e0c-bcfd-8f7209096fa5.pdf', insights: ['OSEP found that the State does not have a reasonably designed general supervision system, including policies and procedures, for subrecipient monitoring and fiscal management, consistent with 2 C.F.R. sections 200.332(b), (d)-(f) and (h), 200.339, and 34 C.F.R. sections 300.149, 300.600 through 602, and 300.604.','OSEP found that the State does not have mechanisms in place to ensure due process hearing decisions are implemented within the timeframe prescribed by the hearing officer, or if there is no timeframe prescribed by the hearing officer, within a reasonable time set by the State, as required by 34 C.F.R. sections 300.149, 300.511 through 300.514, and 300.600.'] },
    ],
    "NY": [
      { part: 'B', date: 'March 2025', iso: '2025-03-26', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/e8533300-f2e1-4e3c-a945-aea2772a8060.pdf', insights: [] },
      { part: 'C', date: 'September 2024', iso: '2024-09-24', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/b2ee1c39-86b5-460c-84c3-ead955ace459.pdf', insights: [] },
      { part: 'B', date: 'May 2024', iso: '2024-05-08', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/c3370d71-ffeb-447f-8419-aaa1223f6c31.pdf', insights: [] },
      { part: 'C', date: 'February 2024', iso: '2024-02-29', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/895fa1d9-0fac-4a26-a1d8-d870ef9a64a4.pdf', insights: ['OSEP found that the State is unable to ensure that early intervention services are provided to all eligible infants and toddlers with disabilities and their families in a timely manner as required by 34 C.F.R. sections 303.112 and 303.342(e), with related findings that needed services are not identified on the IFSP based on the child\'s unique needs under 34 C.F.R. sections 303.13(a), 303.322(c), and 303.344(d) and that services are not available in all geographic areas of the State consistent with 34 C.F.R. section 303.207.','OSEP found deficiencies in the State\'s general supervision system, determining that the State does not identify noncompliance in a timely manner using its data system as required under 34 C.F.R. sections 303.120 and 303.700 through 303.702, and does not verify the correction of all findings of noncompliance related to IDEA Part C beyond the SPP/APR indicators as required under 34 C.F.R. section 303.120 and its monitoring responsibilities in 34 C.F.R. section 303.700(e).'] },
      { part: 'B', date: 'December 2023', iso: '2023-12-21', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/317bf785-cd50-4305-ba1e-f8bbb6adb33c.pdf', insights: [] },
      { part: 'B', date: 'September 2023', iso: '2023-09-21', kind: 'Targeted monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/d86495ce-4065-4848-83b4-811ebc8f5afb.pdf', insights: ['In the area of general supervision, OSEP found that NYSED does not have a general supervision system that is reasonably designed to identify and verify correction of noncompliance in a timely manner using its different components, as required under 34 C.F.R. sections 300.149 and 300.600 through 300.602.','In the area of dispute resolution due process hearings, OSEP found that NYSED does not ensure that public agencies issue timely due process hearing decisions as required in 34 C.F.R. section 300.515, noting that over 50 percent of open cases against New York City Public Schools are beyond the 45-day or properly extended timeline for issuance of a decision.'] },
    ],
    "OR": [
      { part: 'B', date: 'June 2025', iso: '2025-06-11', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/2399fc68-ae92-4ac2-b6ca-a4cec7a48dcd.pdf', insights: ['In the area of fiscal management and subrecipient monitoring, OSEP finds that the State does not have a reasonably designed general supervision system, including policies and procedures, for subrecipient monitoring and fiscal management, consistent with 2 C.F.R. sections 200.332(b), (d) through (f) and (h), 200.339, and 34 C.F.R. sections 300.149, 300.600 through 602, and 300.604.','In the area of general supervision and correction of noncompliance, OSEP finds that the State does not have a mechanism in place for ensuring that a management decision is issued when required for applicable single State audit findings pertaining to IDEA and for determining whether an auditee has completed any required corrective action, in accordance with 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.604.'] },
      { part: 'C', date: 'June 2025', iso: '2025-06-05', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/0cfc76ec-3836-41ba-9187-c9bdd98f6269.pdf', insights: ['OSEP found that the State does not have a reasonably designed general supervision system that includes policies and procedures to monitor early intervention service programs or providers and ensure compliance with IDEA Part C fiscal requirements, such as coordination of all available funding sources and payor of last resort, as required by 2 C.F.R. sections 200.329(a), 200.303, and 34 C.F.R. sections 303.120(a), 303.500 through 303.510, and 303.520 through 303.521.'] },
    ],
    "SC": [
      { part: 'B', date: 'March 2026', iso: '2026-03-25', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/b4cac60b-c202-4a93-b28d-e9222fea0393.pdf', insights: [] },
      { part: 'B', date: 'December 2024', iso: '2024-12-05', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/4679a6f9-e016-47d8-b67f-e7509ac86111.pdf', insights: [] },
      { part: 'B', date: 'April 2024', iso: '2024-04-23', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/aebc6360-023b-487f-b732-ade93452f41a.pdf', insights: ['In the area of general supervision, OSEP found that the State does not have a general supervision system that is reasonably designed to identify noncompliance with all IDEA Part B requirements in a timely manner as required under 34 C.F.R. sections 300.149 and 300.600 through 300.602, because the State relies solely on LEA performance on SPP/APR indicators and does not consistently issue timely, complete written findings of noncompliance.','In the area of correction of noncompliance, OSEP found that the State is not verifying that each LEA identified with noncompliance is correctly implementing the specific regulatory requirements based on a review of updated data and information (systemic compliance), as required under 34 C.F.R. section 300.600(d) and (e).'] },
    ],
    "TN": [
      { part: 'C', date: 'September 2025', iso: '2025-09-10', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/f50372a5-8e96-4601-85a5-d97bc9579438.pdf', insights: ['In the area of general supervision, OSEP found that the State does not have a general supervision system that is reasonably designed to identify noncompliance with all IDEA Part C requirements in a timely manner because it limits programmatic monitoring to the SPP/APR compliance indicators, as required by 34 C.F.R. sections 303.120 and 303.700 through 303.708.','In the area of fiscal management, OSEP found that the State does not have a reasonably designed general supervision system that includes policies and procedures to monitor EIS programs or providers and ensure compliance with IDEA Part C fiscal requirements, such as coordination of all available funding sources and payor of last resort, as required by 34 C.F.R. sections 303.120(a), 303.500 through 303.510, and 303.520 through 303.521, and 2 C.F.R. sections 200.329(a) and 200.303.'] },
      { part: 'B', date: 'July 2025', iso: '2025-07-23', kind: 'Targeted monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/addf9c87-3578-4527-b51e-c0d203d208e3.pdf', insights: ['In the general supervision area of identification of noncompliance, OSEP finds that the State\'s written notification of noncompliance identified through its APR monitoring process does not ensure proper notice to LEAs or include all required content to promote the timely correction of noncompliance, as required by 34 C.F.R. sections 300.149 and 300.600(e).','In the general supervision area of correction of noncompliance, OSEP finds that the State does not have a general supervision system that is reasonably designed to verify correction of noncompliance in a timely manner because it does not confirm that each LEA achieved 100 percent compliance based on a review of updated data, as required under 34 C.F.R. sections 300.149, and 300.600 through 300.602.'] },
    ],
    "TX": [
      { part: 'B', date: 'May 2023', iso: '2023-05-04', kind: 'Closeout letter', url: 'https://www.ed.gov/sites/ed/files/fund/data/report/idea/partbdmsrpts/dms-tx-b-closeout-2023.pdf', insights: [] },
    ],
    "UT": [
      { part: 'C', date: 'March 2026', iso: '2026-03-25', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/91b9806d-86f6-4450-b866-0f6270df90a5.pdf', insights: ['In the area of provision of early intervention services, OSEP found that the State cannot ensure that all early intervention services identified on the individualized family service plans of infants and toddlers with disabilities are individualized to meet the needs of the child and family as determined by the IFSP team, as required by 34 C.F.R. sections 303.13(a), 303.343, and 303.344(d), and that early intervention services are provided to all eligible infants and toddlers with disabilities and their families in a timely manner as required by 34 C.F.R. sections 303.112 and 303.342(e).','In the area of general supervision, OSEP found that the State is not timely identifying noncompliance when monitoring early intervention service programs or providers, as required by 20 U.S.C. sections 1416(a), 1434, 1435(a)(10), 1442, and 34 C.F.R. sections 303.120 and 303.700 through 303.708.'] },
      { part: 'B', date: 'July 2025', iso: '2025-07-14', kind: 'Monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/340ad4e8-47cb-463d-ad33-647def0d6128.pdf', insights: ['In the area of general supervision, OSEP found that the State does not have a general supervision system reasonably designed to identify noncompliance with IDEA Part B requirements in a timely manner because the State limits programmatic monitoring to reviewing individual student files rather than examining local policies, procedures, and practices, as required by 34 C.F.R. sections 300.149, 300.600 through 300.602, and 300.606 through 300.608.','In the area of correction of noncompliance, OSEP found that the State does not have a general supervision system reasonably designed to verify the correction of noncompliance because it applies a "ten percent rule" that allows local educational agencies to self-select evidence and files rather than reviewing updated data to confirm the agency achieved 100 percent compliance, inconsistent with 34 C.F.R. section 300.600(e).'] },
    ],
    "VA": [
      { part: 'B', date: 'December 2024', iso: '2024-12-05', kind: 'Closeout letter', url: 'https://www.specialeducationaction.com/api/v1/file/f9c26962-f480-41b0-a354-49002d3344c2.pdf', insights: [] },
      { part: 'B', date: 'July 2024', iso: '2024-07-18', kind: 'Status letter', url: 'https://www.specialeducationaction.com/api/v1/file/a727f8e2-ba09-41eb-bcdc-24dc78cbbfe7.pdf', insights: [] },
      { part: 'B', date: 'March 2024', iso: '2024-03-13', kind: 'Targeted monitoring report', url: 'https://www.specialeducationaction.com/api/v1/file/69e5bcac-da57-41da-abb2-803393873b9c.pdf', insights: ['OSEP found that, in resolving State complaints, the State does not consistently identify and require correction of all noncompliance with IDEA requirements identified through complaint resolution when the noncompliance was not specifically alleged in the complaint, a practice inconsistent with 34 C.F.R. sections 300.149, 300.151, 300.153, and 300.600 through 300.602 and OSEP guidance.','OSEP found that the State has not ensured that its local educational agencies are implementing the independent educational evaluation requirements in the State\'s revised regulation and in IDEA\'s requirements at 34 C.F.R. section 300.502.'] },
      { part: 'B', date: 'March 2024', iso: '2024-03-13', kind: 'Closeout letter', url: 'https://www.ed.gov/sites/ed/files/fund/data/report/idea/partbdmsrpts/va-b-2023-close%20out-03-13-2024.pdf', insights: [] },
      { part: 'B', date: 'January 2023', iso: '2023-01-17', kind: 'Status letter', url: 'https://www.ed.gov/sites/ed/files/fund/data/report/idea/partbdmsrpts/dms-va-b-2023-letter-01-17-2023.pdf', insights: [] },
    ],
  },
  personnel: {
  "national": {
    "teacherPct": 91.2,
    "teacherFTE": 444915,
    "teacherCertFTE": 405972,
    "relatedPct": 97,
    "relatedFTE": 253386,
    "year": "Fall 2022"
  },
  "byState": {
    "AK": 90.5,
    "AL": 97.8,
    "AR": 86.4,
    "AZ": 93.4,
    "CA": 94.1,
    "CO": 94.4,
    "CT": 94.4,
    "DC": 82.2,
    "DE": 75.9,
    "FL": 100,
    "GA": 95.6,
    "HI": 93.3,
    "IA": 100,
    "ID": 99,
    "IL": 98.9,
    "IN": 73.3,
    "KS": 84.7,
    "KY": 96.4,
    "LA": 74.3,
    "MD": 88,
    "ME": 97.8,
    "MI": 93.2,
    "MN": 82.7,
    "MO": 93.8,
    "MS": 99.4,
    "MT": 75.5,
    "NC": 93.6,
    "ND": 100,
    "NE": 90,
    "NJ": 100,
    "NM": 95.6,
    "NV": 95.5,
    "NY": 81.3,
    "OH": 96.8,
    "OK": 97.6,
    "OR": 82.9,
    "PA": 96.7,
    "RI": 99.1,
    "SC": 98.3,
    "SD": 94,
    "TN": 95.3,
    "TX": 78.1,
    "UT": 91.1,
    "VA": 93.7,
    "VT": 91.5,
    "WA": 96.6,
    "WI": 96.6,
    "WV": 80.4,
    "WY": 90.8
  }
}
};
